### ISSUE TITLE
Link broken in Documentation

### ISSUE THREAD

**Issue by BCsRock** [opengsn/docs#10]
In the section "Running your own production relay server" at the very bottom of the documentation page here: https://docs.opengsn.org/javascript-client/tutorial.html#introduction 

The link in the sentence 
`If you are interested in running your own production relay server on a real network, refer to these instructions.` 
is broken. 

Broken Link : https://docs.opengsn.org/javascript-client/:running-own-relay.html

**Comment by jjperezaguinaga** [comment]
This is already solved, candidate for closing on #14
